### ISSUE TITLE
Wrong Time Tracking at Night

### ISSUE THREAD

**Issue by derduden** [rishibaldawa/TimeSignal#1]
Hello,
yesterday i installed your plugin. I started surfing at around 11PM till 1AM. Then i shut down my computer. Now at 8PM the plugin tells me "9 Hours Spent".

Browser Mozilla Firefox for Ubuntu (canonical - 1.0)

Best regards,

Mathias

**Comment by rishibaldawa** [comment]
That's odd. Let me see why its doing that.

**Comment by rishibaldawa** [comment]
I don't see anything that can make that happen and haven't had it myself. Very odd.

**Comment by derduden** [comment]
i installed time signal 0.3 again (firefox 36.0 on xubuntu 14.04). i use the following setting 15/150/180. the plugin does not work properly on my machine. today, after hours of browser activity the counter was "magically" set to zero. i am not sure but maybe it was after unlocking the screen...

**Comment by derduden** [comment]
right now i started my pc again. after opening firefox the circle is red and when i click on it it says "10 hours spent".

**Comment by rishibaldawa** [comment]
That's odd. I'm going to add some testing to see what's going on. But before that I'll add in a reset and, perhaps, a snooze option to at least correct the plugin manually.

**Comment by rishibaldawa** [comment]
I'm also turning off notifications. They'll just be annoying until I get this fixed.

**Comment by rishibaldawa** [comment]
The change is under review,  if you want you can update manually https://addons.mozilla.org/en-US/firefox/addon/time-signal/versions/?page=1#version-0.4

**Comment by rishibaldawa** [comment]
closing
